name: Run Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          pip install -e .
      - name: Endpoint Test
        run: python tests/nrgcloud_tests/endpoint_check.py
      - name: SymPRO TXT Reader Test
        working-directory: ./nrgpy/
        run: python tests/test_readers/test_sympro_txt_read.py
