name: Run Tests
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  tests:
    strategy:
      matrix:
        version: ["3.9", "3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{matrix.version}}
        uses: actions/setup-python@v1
        with:
          python-version: ${{matrix.version}}.
      - name: Install dependencies
        run: |
          pip install --update pip && && pip install .[test]
      - name: SymPRO TXT Reader Test
        run: python -m tests.readers.test_sympro_txt_read tests/readers/files/
      - name: Endpoint Test
        run: |
          python -m tests.nrgcloud.endpoint
      - name: NRG Cloud API tests
        env:
          CLIENT_ID: ${{ secrets.NRG_CLOUD_API_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.NRG_CLOUD_API_CLIENT_SECRET }}
        run: |
          python -m tests.nrgcloud.api $CLIENT_ID $CLIENT_SECRET
      - name: Pytests
        run: |
          pytest tests/
