name: Run Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -e .
      - name: SymPRO TXT Reader Test
        run: python tests/test_readers/test_sympro_txt_read.py tests/test_readers/test_files/
      - name: Endpoint Test
        run: |
          python tests/nrgcloud_tests/endpoint_check.py
      - name: NRG Cloud API tests
        env:
          CLIENT_ID: ${{ secrets.NRG_CLOUD_API_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.NRG_CLOUD_API_CLIENT_SECRET }}
        run: |
          python tests/nrgcloud_tests/api_tests.py $CLIENT_ID $CLIENT_SECRET
