name: Run Tests
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -e . && pip install pytest
      - name: Utilities pytests
        run: |
          pytest tests/utilities/test_utilities.py
      - name: SymPRO TXT Reader Test
        run: python tests/readers/test_sympro_txt_read.py tests/readers/files/
      - name: Endpoint Test
        run: |
          python tests/nrgcloud/endpoint.py
      - name: NRG Cloud API tests
        env:
          CLIENT_ID: ${{ secrets.NRG_CLOUD_API_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.NRG_CLOUD_API_CLIENT_SECRET }}
        run: |
          python tests/nrgcloud/api.py $CLIENT_ID $CLIENT_SECRET
